dist: trusty
sudo: required
language: cpp
  
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test

env:
    global:
    # should be limited to 4 on travis
    - OMP_NUM_THREADS=4
    # make cmake verbose
    - VERBOSE=1
    
install: sh ci/.travis_install.sh

script: sh ci/.travis_test.sh 
